import React from 'react';
import { FileText, CheckCircle2 } from 'lucide-react';

export const TermsOfService: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      
      <div className="text-center mb-10">
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-red-100 text-red-700 text-xs font-bold mb-3">
          <FileText className="w-3.5 h-3.5" />
          Terms & Conditions
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-gray-900 tracking-tight">
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-gray-500">
          Last Updated: September 2026
        </p>
      </div>

      <div className="bg-white rounded-2xl border border-gray-200 p-8 shadow-xs space-y-6 text-sm text-gray-700 leading-relaxed">
        
        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">1. Agreement to Terms</h2>
          <p>
            By accessing or using <strong>BQ Code Tools</strong>, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">2. Free Commercial & Personal License</h2>
          <p>
            Permission is granted to freely generate, download, print, distribute, and commercially utilize barcodes and QR codes generated by the BQ Code Tools web application. You retain full intellectual property and commercial rights to the graphical codes you generate.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">3. Prohibited Uses</h2>
          <p>
            You agree not to use the service to generate barcodes or QR codes for fraudulent, illegal, or malicious activities, including but not limited to phishing links, malware distribution, or counterfeit trademark infringement.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">4. Disclaimer of Warranties & Scanning Liability</h2>
          <p>
            While BQ Code Tools adheres strictly to ISO and GS1 symbology math, physical scan performance depends heavily on the printer resolution, paper contrast, quiet margins, and hardware optics used. The materials on BQ Code Tools are provided on an 'as is' basis. We recommend test scanning printed samples before mass manufacturing.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">5. Modifications to Terms</h2>
          <p>
            BQ Code Tools may revise these terms of service at any time without prior notice. By using this website you are agreeing to be bound by the current version of these terms.
          </p>
        </section>

      </div>
    </div>
  );
};
